#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Pull Request Labeler Github Action Configuration: https://github.com/marketplace/actions/labeler

"type:infra":
  - ".gitattributes"
  - ".github/**/*"
  - ".gitignore"
  - ".travis.yml"
  - "DISCLAIMER"
  - "LICENSE"
  - "LICENSE-binary"
  - "NOTICE"
  - "NOTICE-binary"
  - "codecov.yml"
  - "dev/**/*"
  - "tools/**/*"

"type:build":
  - "**/*pom.xml"
  - "amoro-ams/dist/**/*"
  - "docker/**/*"
  - "charts/**/"

"type:docs":
  - "*.md"
  - "docs/**/*"

"module:core":
  - "amoro-core/**/*"

"module:ams-server":
  - "amoro-ams/amoro-ams-api/**/*"
  - "amoro-ams/amoro-ams-server/**/*"

"module:ams-dashboard":
  - "amoro-web/**/*"

"module:ams-optimizer":
  - "amoro-optimizer/**/*"

"module:mixed-spark":
  - "amoro-mixed-format/amoro-mixed-format-spark/**/*"

"module:mixed-flink":
  - "amoro-mixed-format/amoro-mixed-format-flink/**/*"

"module:mixed-hive":
  - "amoro-mixed-format/amoro-mixed-format-hive/**/*"

"module:mixed-trino":
  - "amoro-mixed-format/amoro-mixed-format-trino/**/*"
