# .github/release.yml

changelog:
  categories:
    - title: Improves
      labels:
        - 'type:improvement'
      exclude:
        labels:
          - 'type:docs'
    - title: Bugs
      lables:
        - 'type:bug'      
      exclude:
        lables:
          - 'type:docs'
    - title: Document Improvement
      lables:
        - 'type:docs'
