apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
        {{- include "amoro.labels" . | nindent 4 }}
type: Opaque
data:
  # use helm set dashboard username and password
  username: {{ .Values.amoroConf.ams.adminUsername | b64enc | quote }}
  password: {{ .Values.amoroConf.ams.adminPassword | b64enc | quote }}