[request_definition]
r = sub, resType, resId, act

[policy_definition]
p = sub, resType, resId, act, eft

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = r.sub == p.sub && r.resType == p.resType && r.resId == p.resId && r.act == p.act
