{
 "title": "Amoro Metrics Dashboard",
 "tags": [ "Amoro" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Catalog",
    "query": {
     "query": "label_values(amoro_table_optimizing_process_total_count_total,catalog)"
    }
   },
   {
    "name": "Database",
    "query": {
     "query": "label_values(amoro_table_optimizing_process_total_count_total{catalog=~\"$Catalog\"},database)"
    }
   },
   {
    "name": "Table",
    "query": {
     "query": "label_values(amoro_table_optimizing_process_total_count_total{catalog=~\"$Catalog\", database=~\"$Database\"},table)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Optimizer Information",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(amoro_optimizer_group_optimizer_instances)",
     "legendFormat": "Instance"
    },
    {
     "expr": "sum(amoro_optimizer_group_memory_bytes_allocated)",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(amoro_optimizer_group_threads)",
     "legendFormat": "Thread"
    }
   ]
  },
  {
   "title": "Table Current Stat",
   "type": "stat",
   "description": "Table Current Stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(amoro_table_optimizing_status_in_idle)",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(amoro_table_optimizing_status_in_planning)",
     "legendFormat": "Planning"
    },
    {
     "expr": "sum(amoro_table_optimizing_status_in_executing)",
     "legendFormat": "Executing"
    },
    {
     "expr": "sum(amoro_table_optimizing_status_in_pending)",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(amoro_table_optimizing_status_in_committing)",
     "legendFormat": "Committing"
    }
   ]
  },
  {
   "title": "All Process Count",
   "type": "stat",
   "description": "Count of all optimizing process since ams started",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(catalog) (amoro_table_optimizing_process_total_count_total)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(catalog) (amoro_table_optimizing_process_failed_count_total)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Minor Process Count",
   "type": "stat",
   "description": "Count of Minor optimizing process since ams started",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(catalog) (amoro_table_optimizing_minor_total_count_total)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(catalog) (amoro_table_optimizing_minor_failed_count_total)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Major Process Count",
   "type": "stat",
   "description": "Count of Major optimizing process since ams started",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(catalog) (amoro_table_optimizing_major_total_count_total)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(catalog) (amoro_table_optimizing_major_failed_count_total)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Full Process Count",
   "type": "stat",
   "description": "Count of full optimizing process since ams started",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(catalog) (amoro_table_optimizing_full_total_count_total)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(catalog) (amoro_table_optimizing_full_failed_count_total)",
     "legendFormat": "Failed"
    }
   ]
  },
  { "title": "Self Optimizing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Planning Duration",
   "type": "timeseries",
   "description": "Duration in milliseconds after table be in planning status",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(amoro_table_optimizing_status_planning_duration_mills{catalog=~\"$Catalog\", database=~\"$Database\", table=~\"$Table\"})",
     "legendFormat": "sum(table_optimizing_status_planning_duration_mills)"
    }
   ]
  },
  {
   "title": "Top Planning Duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "amoro_table_optimizing_status_planning_duration_mills{catalog=~\"$Catalog\", database=~\"$Database\", table=~\"$Table\"} > 0",
     "legendFormat": "{{catalog}}.{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Pending Duration",
   "type": "timeseries",
   "description": "Duration in milliseconds after table be in pending status",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(amoro_table_optimizing_status_pending_duration_mills{catalog=~\"$Catalog\", database=~\"$Database\", table=~\"$Table\"})",
     "legendFormat": "sum(table_optimizing_status_pending_duration_mills)"
    }
   ]
  },
  {
   "title": "Top Pending Duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "amoro_table_optimizing_status_pending_duration_mills{catalog=~\"$Catalog\", database=~\"$Database\", table=~\"$Table\"} > 0",
     "legendFormat": "{{catalog}}.{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Executing Duration",
   "type": "timeseries",
   "description": "Duration in milliseconds after table be in executing status",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(amoro_table_optimizing_status_executing_duration_mills{catalog=~\"$Catalog\", database=~\"$Database\", table=~\"$Table\"})",
     "legendFormat": "sum(table_optimizing_status_executing_duration_mills)"
    }
   ]
  },
  {
   "title": "Top Executing Duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "amoro_table_optimizing_status_executing_duration_mills{catalog=~\"$Catalog\", database=~\"$Database\", table=~\"$Table\"} > 0",
     "legendFormat": "{{catalog}}.{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Committing Duration",
   "type": "timeseries",
   "description": "Duration in milliseconds after table be in Committing status",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(amoro_table_optimizing_status_committing_duration_mills{catalog=~\"$Catalog\", database=~\"$Database\", table=~\"$Table\"})",
     "legendFormat": "sum(table_optimizing_status_committing_duration_mills)"
    }
   ]
  },
  {
   "title": "Top Committing Duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "amoro_table_optimizing_status_committing_duration_mills{catalog=~\"$Catalog\", database=~\"$Database\", table=~\"$Table\"} ",
     "legendFormat": "{{catalog}}.{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Top Total Count",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "amoro_table_optimizing_process_total_count_total{catalog=~\"$Catalog\", database=~\"$Database\", table=~\"$Table\"} > 0",
     "legendFormat": "{{catalog}}.{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Top Minor Count",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "amoro_table_optimizing_minor_total_count_total{catalog=~\"$Catalog\", database=~\"$Database\", table=~\"$Table\"} > 0",
     "legendFormat": "{{catalog}}.{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Top Major Count",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "amoro_table_optimizing_major_total_count_total{catalog=~\"$Catalog\", database=~\"$Database\", table=~\"$Table\"} > 0",
     "legendFormat": "{{catalog}}.{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Top Full Count",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "amoro_table_optimizing_full_total_count_total{catalog=~\"$Catalog\", database=~\"$Database\", table=~\"$Table\"} > 0",
     "legendFormat": "{{catalog}}.{{database}}.{{table}}"
    }
   ]
  },
  { "title": "Optimizer Group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Planing Table Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "amoro_optimizer_group_planing_tables",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Pending Table Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
   "targets": [
    {
     "expr": "amoro_optimizer_group_pending_tables",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Executing Table Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
   "targets": [
    {
     "expr": "amoro_optimizer_group_executing_tables",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Pending Task Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "amoro_optimizer_group_pending_tasks",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Executing Task Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "amoro_optimizer_group_executing_tasks",
     "legendFormat": "{{group}}"
    }
   ]
  }
 ]
}