/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.amoro.formats.paimon.optimizing;

import org.apache.amoro.formats.paimon.PaimonTable;
import org.apache.amoro.optimizing.BaseOptimizingInput;
import org.apache.amoro.shade.guava32.com.google.common.base.MoreObjects;

/**
 * Compaction input for Paimon BUCKET_UNAWARE (AppendOnly) tables.
 *
 * <p>Carries everything the Optimizer side needs to execute one {@code AppendCompactTask}:
 *
 * <ul>
 *   <li>{@link #table} — the Paimon AmoroTable wrapper, directly serialized into this input à la
 *       {@code RewriteFilesInput#table} on the Iceberg side.
 *   <li>{@link #taskBytes} — the serialized {@code AppendCompactTask} (see {@code
 *       AppendCompactTaskSerializer}).
 *   <li>{@link #serializerVersion} — the version used by the serializer, enabling forward
 *       compatibility across Paimon upgrades.
 *   <li>{@link #commitUser} — UUID generated by the Planner and persisted into {@code
 *       TableProcessStore.properties}; shared by all tasks in one plan and across retries so that
 *       Paimon's built-in idempotency ({@code user + identifier}) deduplicates stale commits.
 *   <li>{@link #partitionPath} — human-readable partition path, used only for metrics/logging.
 *   <li>{@link #targetSnapshotId} — the snapshot id the plan was based on; used for drift detection
 *       during commit.
 * </ul>
 */
public class PaimonCompactionInput extends BaseOptimizingInput {

  private static final long serialVersionUID = 1L;

  private PaimonTable table;
  private byte[] taskBytes;
  private int serializerVersion;
  private String commitUser;
  private String partitionPath;
  private long targetSnapshotId;

  public PaimonCompactionInput() {}

  public PaimonCompactionInput(
      PaimonTable table,
      byte[] taskBytes,
      int serializerVersion,
      String commitUser,
      String partitionPath,
      long targetSnapshotId) {
    this.table = table;
    this.taskBytes = taskBytes;
    this.serializerVersion = serializerVersion;
    this.commitUser = commitUser;
    this.partitionPath = partitionPath;
    this.targetSnapshotId = targetSnapshotId;
  }

  public PaimonTable getTable() {
    return table;
  }

  public byte[] getTaskBytes() {
    return taskBytes;
  }

  public int getSerializerVersion() {
    return serializerVersion;
  }

  public String getCommitUser() {
    return commitUser;
  }

  public String getPartitionPath() {
    return partitionPath;
  }

  public long getTargetSnapshotId() {
    return targetSnapshotId;
  }

  @Override
  public String toString() {
    return MoreObjects.toStringHelper(this)
        .add("table", table == null ? null : table.id())
        .add("taskBytesLen", taskBytes == null ? 0 : taskBytes.length)
        .add("serializerVersion", serializerVersion)
        .add("commitUser", commitUser)
        .add("partitionPath", partitionPath)
        .add("targetSnapshotId", targetSnapshotId)
        .addValue(super.toString())
        .toString();
  }
}
