#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Modified by Datazip Inc. in 2026

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: fusion-cluster
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  disableDefaultCNI: false
nodes:
  - role: control-plane
    image: kindest/node:v1.28.0
    extraMounts:
      - hostPath: FUSION_LOG_PLACEHOLDER
        containerPath: /mnt/fusion-logs
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
      - |
        kind: ClusterConfiguration
        apiServer:
          certSANs:
            - "127.0.0.1"
            - "0.0.0.0"
            - "localhost"
            - "fusion-cluster-control-plane"
  - role: worker
    image: kindest/node:v1.28.0
    extraMounts:
      - hostPath: FUSION_LOG_PLACEHOLDER
        containerPath: /mnt/fusion-logs
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            max-pods: "110"
  - role: worker
    image: kindest/node:v1.28.0
    extraMounts:
      - hostPath: FUSION_LOG_PLACEHOLDER
        containerPath: /mnt/fusion-logs
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            max-pods: "110"
