/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.netease.arctic.ams.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2022-10-27")
public class OptimizerMetric implements org.apache.thrift.TBase<OptimizerMetric, OptimizerMetric._Fields>, java.io.Serializable, Cloneable, Comparable<OptimizerMetric> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("OptimizerMetric");

  private static final org.apache.thrift.protocol.TField OPTIMIZER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("optimizerId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField SUBTASK_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("subtaskId", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField METRIC_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("metricName", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField METRIC_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("metricValue", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new OptimizerMetricStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new OptimizerMetricTupleSchemeFactory();

  public long optimizerId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String subtaskId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String metricName; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String metricValue; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    OPTIMIZER_ID((short)1, "optimizerId"),
    SUBTASK_ID((short)2, "subtaskId"),
    METRIC_NAME((short)3, "metricName"),
    METRIC_VALUE((short)4, "metricValue");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // OPTIMIZER_ID
          return OPTIMIZER_ID;
        case 2: // SUBTASK_ID
          return SUBTASK_ID;
        case 3: // METRIC_NAME
          return METRIC_NAME;
        case 4: // METRIC_VALUE
          return METRIC_VALUE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __OPTIMIZERID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.OPTIMIZER_ID, new org.apache.thrift.meta_data.FieldMetaData("optimizerId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.SUBTASK_ID, new org.apache.thrift.meta_data.FieldMetaData("subtaskId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.METRIC_NAME, new org.apache.thrift.meta_data.FieldMetaData("metricName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.METRIC_VALUE, new org.apache.thrift.meta_data.FieldMetaData("metricValue", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(OptimizerMetric.class, metaDataMap);
  }

  public OptimizerMetric() {
  }

  public OptimizerMetric(
    long optimizerId,
    java.lang.String subtaskId,
    java.lang.String metricName,
    java.lang.String metricValue)
  {
    this();
    this.optimizerId = optimizerId;
    setOptimizerIdIsSet(true);
    this.subtaskId = subtaskId;
    this.metricName = metricName;
    this.metricValue = metricValue;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public OptimizerMetric(OptimizerMetric other) {
    __isset_bitfield = other.__isset_bitfield;
    this.optimizerId = other.optimizerId;
    if (other.isSetSubtaskId()) {
      this.subtaskId = other.subtaskId;
    }
    if (other.isSetMetricName()) {
      this.metricName = other.metricName;
    }
    if (other.isSetMetricValue()) {
      this.metricValue = other.metricValue;
    }
  }

  public OptimizerMetric deepCopy() {
    return new OptimizerMetric(this);
  }

  @Override
  public void clear() {
    setOptimizerIdIsSet(false);
    this.optimizerId = 0;
    this.subtaskId = null;
    this.metricName = null;
    this.metricValue = null;
  }

  public long getOptimizerId() {
    return this.optimizerId;
  }

  public OptimizerMetric setOptimizerId(long optimizerId) {
    this.optimizerId = optimizerId;
    setOptimizerIdIsSet(true);
    return this;
  }

  public void unsetOptimizerId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __OPTIMIZERID_ISSET_ID);
  }

  /** Returns true if field optimizerId is set (has been assigned a value) and false otherwise */
  public boolean isSetOptimizerId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __OPTIMIZERID_ISSET_ID);
  }

  public void setOptimizerIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __OPTIMIZERID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getSubtaskId() {
    return this.subtaskId;
  }

  public OptimizerMetric setSubtaskId(@org.apache.thrift.annotation.Nullable java.lang.String subtaskId) {
    this.subtaskId = subtaskId;
    return this;
  }

  public void unsetSubtaskId() {
    this.subtaskId = null;
  }

  /** Returns true if field subtaskId is set (has been assigned a value) and false otherwise */
  public boolean isSetSubtaskId() {
    return this.subtaskId != null;
  }

  public void setSubtaskIdIsSet(boolean value) {
    if (!value) {
      this.subtaskId = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getMetricName() {
    return this.metricName;
  }

  public OptimizerMetric setMetricName(@org.apache.thrift.annotation.Nullable java.lang.String metricName) {
    this.metricName = metricName;
    return this;
  }

  public void unsetMetricName() {
    this.metricName = null;
  }

  /** Returns true if field metricName is set (has been assigned a value) and false otherwise */
  public boolean isSetMetricName() {
    return this.metricName != null;
  }

  public void setMetricNameIsSet(boolean value) {
    if (!value) {
      this.metricName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getMetricValue() {
    return this.metricValue;
  }

  public OptimizerMetric setMetricValue(@org.apache.thrift.annotation.Nullable java.lang.String metricValue) {
    this.metricValue = metricValue;
    return this;
  }

  public void unsetMetricValue() {
    this.metricValue = null;
  }

  /** Returns true if field metricValue is set (has been assigned a value) and false otherwise */
  public boolean isSetMetricValue() {
    return this.metricValue != null;
  }

  public void setMetricValueIsSet(boolean value) {
    if (!value) {
      this.metricValue = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case OPTIMIZER_ID:
      if (value == null) {
        unsetOptimizerId();
      } else {
        setOptimizerId((java.lang.Long)value);
      }
      break;

    case SUBTASK_ID:
      if (value == null) {
        unsetSubtaskId();
      } else {
        setSubtaskId((java.lang.String)value);
      }
      break;

    case METRIC_NAME:
      if (value == null) {
        unsetMetricName();
      } else {
        setMetricName((java.lang.String)value);
      }
      break;

    case METRIC_VALUE:
      if (value == null) {
        unsetMetricValue();
      } else {
        setMetricValue((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case OPTIMIZER_ID:
      return getOptimizerId();

    case SUBTASK_ID:
      return getSubtaskId();

    case METRIC_NAME:
      return getMetricName();

    case METRIC_VALUE:
      return getMetricValue();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case OPTIMIZER_ID:
      return isSetOptimizerId();
    case SUBTASK_ID:
      return isSetSubtaskId();
    case METRIC_NAME:
      return isSetMetricName();
    case METRIC_VALUE:
      return isSetMetricValue();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof OptimizerMetric)
      return this.equals((OptimizerMetric)that);
    return false;
  }

  public boolean equals(OptimizerMetric that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_optimizerId = true;
    boolean that_present_optimizerId = true;
    if (this_present_optimizerId || that_present_optimizerId) {
      if (!(this_present_optimizerId && that_present_optimizerId))
        return false;
      if (this.optimizerId != that.optimizerId)
        return false;
    }

    boolean this_present_subtaskId = true && this.isSetSubtaskId();
    boolean that_present_subtaskId = true && that.isSetSubtaskId();
    if (this_present_subtaskId || that_present_subtaskId) {
      if (!(this_present_subtaskId && that_present_subtaskId))
        return false;
      if (!this.subtaskId.equals(that.subtaskId))
        return false;
    }

    boolean this_present_metricName = true && this.isSetMetricName();
    boolean that_present_metricName = true && that.isSetMetricName();
    if (this_present_metricName || that_present_metricName) {
      if (!(this_present_metricName && that_present_metricName))
        return false;
      if (!this.metricName.equals(that.metricName))
        return false;
    }

    boolean this_present_metricValue = true && this.isSetMetricValue();
    boolean that_present_metricValue = true && that.isSetMetricValue();
    if (this_present_metricValue || that_present_metricValue) {
      if (!(this_present_metricValue && that_present_metricValue))
        return false;
      if (!this.metricValue.equals(that.metricValue))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(optimizerId);

    hashCode = hashCode * 8191 + ((isSetSubtaskId()) ? 131071 : 524287);
    if (isSetSubtaskId())
      hashCode = hashCode * 8191 + subtaskId.hashCode();

    hashCode = hashCode * 8191 + ((isSetMetricName()) ? 131071 : 524287);
    if (isSetMetricName())
      hashCode = hashCode * 8191 + metricName.hashCode();

    hashCode = hashCode * 8191 + ((isSetMetricValue()) ? 131071 : 524287);
    if (isSetMetricValue())
      hashCode = hashCode * 8191 + metricValue.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(OptimizerMetric other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetOptimizerId()).compareTo(other.isSetOptimizerId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOptimizerId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.optimizerId, other.optimizerId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSubtaskId()).compareTo(other.isSetSubtaskId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSubtaskId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.subtaskId, other.subtaskId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetMetricName()).compareTo(other.isSetMetricName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMetricName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.metricName, other.metricName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetMetricValue()).compareTo(other.isSetMetricValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMetricValue()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.metricValue, other.metricValue);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("OptimizerMetric(");
    boolean first = true;

    sb.append("optimizerId:");
    sb.append(this.optimizerId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("subtaskId:");
    if (this.subtaskId == null) {
      sb.append("null");
    } else {
      sb.append(this.subtaskId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("metricName:");
    if (this.metricName == null) {
      sb.append("null");
    } else {
      sb.append(this.metricName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("metricValue:");
    if (this.metricValue == null) {
      sb.append("null");
    } else {
      sb.append(this.metricValue);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class OptimizerMetricStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public OptimizerMetricStandardScheme getScheme() {
      return new OptimizerMetricStandardScheme();
    }
  }

  private static class OptimizerMetricStandardScheme extends org.apache.thrift.scheme.StandardScheme<OptimizerMetric> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, OptimizerMetric struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // OPTIMIZER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.optimizerId = iprot.readI64();
              struct.setOptimizerIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SUBTASK_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.subtaskId = iprot.readString();
              struct.setSubtaskIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // METRIC_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.metricName = iprot.readString();
              struct.setMetricNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // METRIC_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.metricValue = iprot.readString();
              struct.setMetricValueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, OptimizerMetric struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(OPTIMIZER_ID_FIELD_DESC);
      oprot.writeI64(struct.optimizerId);
      oprot.writeFieldEnd();
      if (struct.subtaskId != null) {
        oprot.writeFieldBegin(SUBTASK_ID_FIELD_DESC);
        oprot.writeString(struct.subtaskId);
        oprot.writeFieldEnd();
      }
      if (struct.metricName != null) {
        oprot.writeFieldBegin(METRIC_NAME_FIELD_DESC);
        oprot.writeString(struct.metricName);
        oprot.writeFieldEnd();
      }
      if (struct.metricValue != null) {
        oprot.writeFieldBegin(METRIC_VALUE_FIELD_DESC);
        oprot.writeString(struct.metricValue);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class OptimizerMetricTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public OptimizerMetricTupleScheme getScheme() {
      return new OptimizerMetricTupleScheme();
    }
  }

  private static class OptimizerMetricTupleScheme extends org.apache.thrift.scheme.TupleScheme<OptimizerMetric> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, OptimizerMetric struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetOptimizerId()) {
        optionals.set(0);
      }
      if (struct.isSetSubtaskId()) {
        optionals.set(1);
      }
      if (struct.isSetMetricName()) {
        optionals.set(2);
      }
      if (struct.isSetMetricValue()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetOptimizerId()) {
        oprot.writeI64(struct.optimizerId);
      }
      if (struct.isSetSubtaskId()) {
        oprot.writeString(struct.subtaskId);
      }
      if (struct.isSetMetricName()) {
        oprot.writeString(struct.metricName);
      }
      if (struct.isSetMetricValue()) {
        oprot.writeString(struct.metricValue);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, OptimizerMetric struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.optimizerId = iprot.readI64();
        struct.setOptimizerIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.subtaskId = iprot.readString();
        struct.setSubtaskIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.metricName = iprot.readString();
        struct.setMetricNameIsSet(true);
      }
      if (incoming.get(3)) {
        struct.metricValue = iprot.readString();
        struct.setMetricValueIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

