name: Olake Driver Releaser

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "tag to release"
        required: true

jobs:
  build_all_drivers:
    if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master')
    name: Build and Release Drivers
    uses: ./.github/workflows/docker-images.yml
    with:
      tag: ${{ github.event.inputs.tag || github.event.release.tag_name }}
    secrets: inherit